#! /bin/sh

bspdir="$HOME/.config/bspwm"
polydir="$HOME/.config/bspwm/rices/$RICETHEME/polybar"
export defnetif=$(ip route | grep '^default' | awk '{print $5}' | head -n1)

BSPWM_BORDER='0'
BSPWM_GAP='8'

function launch() {
  local running
  running="$(pidof -x "$1")"
  [ "$running" ] && kill -9 $(pgrep -x $1) 2> /dev/null
  eval "$* &"
}

function killeww() {
  if [[ `pidof eww` ]]; then 
		pkill eww
  fi
}

function ResetKitty() {
  if [[ `pidof kitty` ]]; then 
		killall -USR1 kitty
  fi
}

function ReloadKitty() {
  if [ -f "$HOME/.config/kitty/current-theme.conf" ]; then
		cat $HOME/.config/bspwm/rices/$RICETHEME/current-theme.conf > $HOME/.config/kitty/current-theme.conf
		ResetKitty
  else
		mkdir -p $HOME/.config/kitty/ && touch $HOME/.config/kitty/current-theme.conf
		cat $HOME/.config/bspwm/rices/$RICETHEME/current-theme.conf > $HOME/.config/kitty/current-theme.conf
		ResetKitty
  fi
}

function SetBspwmConf() {
	bspc config border_width "$BSPWM_BORDER"
	bspc config top_padding "$2"
	bspc config bottom_padding "$3"
	bspc config normal_border_color "$4" 
	bspc config active_border_color "$5"
	bspc config focused_border_color "$6"
	bspc config presel_feedback_color "$7"
	bspc config left_padding "$8"
	bspc config right_padding "$9"
  bspc config window_gap "$BSPWM_GAP"
}

function SetRices() {
	
	case $RICETHEME in
	
		emilia)
		
		  SetBspwmConf "$BSPWM_BORDER" 60 5 "#414868" "#c0caf5" "#bb9af7" "#7aa2f7" 5 5 "$BSPWM_GAP"
		  		  
		  killeww
		  launch polybar -q emi-bar -c ${polydir}/config.ini
		  launch dunst -config ${bspdir}/dunstrc-dark 
		  
		  ;;
			
		jan)
		
		  SetBspwmConf "$BSPWM_BORDER" 60 5 "#4C3A6D" "#4C3A6D" "#785DA5" "#070219" 5 5 "$BSPWM_GAP"
		  
		  killeww
		  launch polybar -q main -c ${polydir}/config.ini
		  launch dunst -config ${bspdir}/dunstrc-dark 
		  
		  ;;
		    
		aline)
		
		  SetBspwmConf "$BSPWM_BORDER" 55 5 "#ca9ee6" "#ca9ee6" "#8CAAEE" "#E78284" 5 5 "$BSPWM_GAP"
		  
		  killeww
		  launch polybar -q aline-bar -c ${polydir}/config.ini
		  launch dunst -config ${bspdir}/dunstrc-light 
		  
		  ;;
		  
		isabel)
		
		  SetBspwmConf "$BSPWM_BORDER" 5 45 "#b8bfe5" "#b8bfe5" "#7560d3" "#81ae5f" 5 5 "$BSPWM_GAP" 
		  
		  killeww
		  launch polybar -q isa-bar -c ${polydir}/config.ini
		  launch dunst -config ${bspdir}/dunstrc-dark 
		  
		  ;;
		  
		cynthia)
		
		  SetBspwmConf "$BSPWM_BORDER" 50 5 "#543f66" "#543f66" "#465b80" "#3f5273" 5 5 "$BSPWM_GAP"
		  
		  killeww
		  launch polybar -q cyn-bar -c ${polydir}/config.ini
		  launch dunst -config ${bspdir}/dunstrc-dark 
		  
		  ;;
		  
		silvia)
		
		  SetBspwmConf "$BSPWM_BORDER" 50 5 "#d3869b" "#d3869b" "#fbf1c7" "#b8bb26" 5 5 "$BSPWM_GAP"

		  killeww
		  launch polybar -q cata-bar -c ${polydir}/config.ini
		  launch dunst -config ${bspdir}/dunstrc-dark 
		  
		  ;;
		
		melissa)
		
		  SetBspwmConf "$BSPWM_BORDER" 42 40 "#e5e9f0" "#e5e9f0" "#4c566a" "#bf616a" 5 5 "$BSPWM_GAP"

		  killeww
		  launch polybar -q mel-bar -c ${polydir}/config.ini
		  polybar -q mel2-bar -c ${polydir}/config.ini &
		  launch dunst -config ${bspdir}/dunstrc-dark
		  
		  ;;
		  
		pamela)
		
		  SetBspwmConf "$BSPWM_BORDER" 60 5 "#C574DD" "#C574DD" "#8897F4" "#FF4971" 5 5 "$BSPWM_GAP"
		  
		  killeww
		  launch polybar -q pam1 -c ${polydir}/config.ini
		  polybar -q pam2 -c ${polydir}/config.ini &
		  polybar -q pam3 -c ${polydir}/config.ini &
		  polybar -q pam4 -c ${polydir}/config.ini &
		  polybar -q pam5 -c ${polydir}/config.ini &
		  polybar -q pam6 -c ${polydir}/config.ini &
		  launch dunst -config ${bspdir}/dunstrc-dark 
		  
		  ;;
		  
		cristina)
		
		  SetBspwmConf "$BSPWM_BORDER" 10 60 "#9bced7" "#9bced7" "#c3a5e6" "#c3a5e6" 5 5 "$BSPWM_GAP"
		  
		  killeww
		  launch polybar -q cristina-bar -c ${polydir}/config.ini
		  launch dunst -config ${bspdir}/dunstrc-dark &
		  
		  ;;
		  
		koichi)
		
		  SetBspwmConf "$BSPWM_BORDER" 5 5 "#3d414f" "#3d414f" "#3d414f" "#90ceaa" 80 5 "$BSPWM_GAP"
		  
		  killall -9 picom bspc
		  
		  launch eww -c $HOME/.config/bspwm/rices/koichi/bar open bar
		  launch polybar -q tray -c ~/.config/bspwm/rices/koichi/bar/polybar_tray.ini
		  launch dunst -config ${bspdir}/dunstrc-dark &
		  
		  ;;
		  
		  karla)
		
		  SetBspwmConf "$BSPWM_BORDER" 65 5 "#ff004a" "#ff004a" "#0864f1" "#b93fe0" 5 5 "$BSPWM_GAP"
		 
      kill -9 picom
		  launch eww -c $HOME/.config/bspwm/rices/karla/bar open bar
		  launch polybar -q karla-bar -c ${polydir}/config.ini
		  polybar -q karla-bar2 -c ${polydir}/config.ini &
		  launch dunst -config ${bspdir}/dunstrc-light		  
		  ;;
		  
		andrea)
		
		  SetBspwmConf "$BSPWM_BORDER" 60 5 "#161616" "#161616" "#605692" "#67d4f1" 5 5 "$BSPWM_GAP"
		  
      killall -9 picom polybar
		  launch dunst -config ${bspdir}/dunstrc-light &
		  launch eww -c $HOME/.config/bspwm/rices/$RICETHEME/arin --restart open-many \
		   search \
		   apps \
		   weather \
		   music \
		   system
		  
		  ;;
		  
	esac		
}

ReloadKitty

function AutoStartApps() {
	
	launch sxhkd -c ${bspdir}/sxhkdrc
	launch picom --config ${bspdir}/rices/$RICETHEME/picom.conf
  RandomWall
	xsetroot -cursor_name left_ptr
	
}
